/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.projempsoft;

/**
 *
 * @author Brunna
 */
public class CadastroDeProdutos extends javax.swing.JFrame {

    /**
     * Creates new form CadastroDeProdutos
     */
    public CadastroDeProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadastraCliente1 = new javax.swing.JButton();
        botaoRegistra1 = new javax.swing.JButton();
        botaoCadastraProduto1 = new javax.swing.JButton();
        botaoRelatorio1 = new javax.swing.JButton();
        botaoRecomenda1 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoCadastraCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/b1se.png"))); // NOI18N
        botaoCadastraCliente1.setToolTipText("Cadastro de Clientes");
        botaoCadastraCliente1.setBorderPainted(false);
        botaoCadastraCliente1.setContentAreaFilled(false);
        botaoCadastraCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastraCliente1ActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCadastraCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 370, 50));

        botaoRegistra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/b2se.png"))); // NOI18N
        botaoRegistra1.setToolTipText("Registro de Vendas");
        botaoRegistra1.setBorderPainted(false);
        botaoRegistra1.setContentAreaFilled(false);
        getContentPane().add(botaoRegistra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 330, 70));

        botaoCadastraProduto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/b3se.png"))); // NOI18N
        botaoCadastraProduto1.setToolTipText("Cadastro de Produtos");
        botaoCadastraProduto1.setBorderPainted(false);
        botaoCadastraProduto1.setContentAreaFilled(false);
        getContentPane().add(botaoCadastraProduto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 330, 90));

        botaoRelatorio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/b4se.png"))); // NOI18N
        botaoRelatorio1.setToolTipText("Relatório de Vendas");
        botaoRelatorio1.setBorderPainted(false);
        botaoRelatorio1.setContentAreaFilled(false);
        getContentPane().add(botaoRelatorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 330, 50));

        botaoRecomenda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/b5se.png"))); // NOI18N
        botaoRecomenda1.setToolTipText("Recomendações de Produtos");
        botaoRecomenda1.setBorderPainted(false);
        botaoRecomenda1.setContentAreaFilled(false);
        botaoRecomenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRecomenda1ActionPerformed(evt);
            }
        });
        getContentPane().add(botaoRecomenda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 350, 80));

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setText("Quantidade");
        jTextField8.setBorder(null);
        jTextField8.setOpaque(false);
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, 110, 30));

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setText("Descrição");
        jTextField7.setBorder(null);
        jTextField7.setOpaque(false);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 110, 30));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setText("Produto");
        jTextField6.setBorder(null);
        jTextField6.setOpaque(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 110, 30));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Cadastro de Produtos");
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 510, 70));

        jScrollPane5.setBorder(null);

        jTextArea5.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 554, 280, 100));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/pesquisar. cad produtos - Cópia.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 670, 130, 70));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/b7se - Cópia_1.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 670, 140, 70));

        jScrollPane1.setBorder(null);

        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 184, 280, -1));

        jScrollPane2.setBorder(null);

        jTextArea2.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 310, 270, -1));

        jScrollPane3.setBorder(null);

        jTextArea3.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 434, 270, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/produtos.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastraCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastraCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastraCliente1ActionPerformed

    private void botaoRecomenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRecomenda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoRecomenda1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDeProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDeProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDeProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDeProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastraCliente1;
    private javax.swing.JButton botaoCadastraProduto1;
    private javax.swing.JButton botaoRecomenda1;
    private javax.swing.JButton botaoRegistra1;
    private javax.swing.JButton botaoRelatorio1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
