/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.projempsoft;

/**
 *
 * @author Dandara
 */
public class MostraCliente extends javax.swing.JFrame {

    /**
     * Creates new form MostraCliente
     */
    public MostraCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadastraCliente1 = new javax.swing.JButton();
        botaoRegistra1 = new javax.swing.JButton();
        botaoCadastraProduto1 = new javax.swing.JButton();
        botaoRelatorio1 = new javax.swing.JButton();
        botaoRecomenda1 = new javax.swing.JButton();
        historico1 = new javax.swing.JTextField();
        historico2 = new javax.swing.JTextField();
        historico3 = new javax.swing.JTextField();
        historico4 = new javax.swing.JTextField();
        historico5 = new javax.swing.JTextField();
        historico6 = new javax.swing.JTextField();
        historico7 = new javax.swing.JTextField();
        dadosCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoCadastraCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/b1se.png"))); // NOI18N
        botaoCadastraCliente1.setToolTipText("Cadastro de Clientes");
        botaoCadastraCliente1.setBorderPainted(false);
        botaoCadastraCliente1.setContentAreaFilled(false);
        botaoCadastraCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastraCliente1ActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCadastraCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 370, 50));

        botaoRegistra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/b2se.png"))); // NOI18N
        botaoRegistra1.setToolTipText("Registro de Vendas");
        botaoRegistra1.setBorderPainted(false);
        botaoRegistra1.setContentAreaFilled(false);
        getContentPane().add(botaoRegistra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 330, 70));

        botaoCadastraProduto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/b3se.png"))); // NOI18N
        botaoCadastraProduto1.setToolTipText("Cadastro de Produtos");
        botaoCadastraProduto1.setBorderPainted(false);
        botaoCadastraProduto1.setContentAreaFilled(false);
        getContentPane().add(botaoCadastraProduto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 330, 90));

        botaoRelatorio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/b4se.png"))); // NOI18N
        botaoRelatorio1.setToolTipText("Relatório de Vendas");
        botaoRelatorio1.setBorderPainted(false);
        botaoRelatorio1.setContentAreaFilled(false);
        getContentPane().add(botaoRelatorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 330, 50));

        botaoRecomenda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/b5se.png"))); // NOI18N
        botaoRecomenda1.setToolTipText("Recomendações de Produtos");
        botaoRecomenda1.setBorderPainted(false);
        botaoRecomenda1.setContentAreaFilled(false);
        botaoRecomenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRecomenda1ActionPerformed(evt);
            }
        });
        getContentPane().add(botaoRecomenda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 350, 80));

        historico1.setBorder(null);
        historico1.setOpaque(false);
        historico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historico1ActionPerformed(evt);
            }
        });
        getContentPane().add(historico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 330, 30));

        historico2.setBorder(null);
        historico2.setOpaque(false);
        historico2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historico2ActionPerformed(evt);
            }
        });
        getContentPane().add(historico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 330, 30));

        historico3.setBorder(null);
        historico3.setOpaque(false);
        getContentPane().add(historico3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 330, 30));

        historico4.setBorder(null);
        historico4.setOpaque(false);
        getContentPane().add(historico4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 330, 30));

        historico5.setBorder(null);
        historico5.setOpaque(false);
        getContentPane().add(historico5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 330, 30));

        historico6.setBorder(null);
        historico6.setOpaque(false);
        historico6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historico6ActionPerformed(evt);
            }
        });
        getContentPane().add(historico6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, 330, 30));

        historico7.setBorder(null);
        historico7.setOpaque(false);
        historico7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historico7ActionPerformed(evt);
            }
        });
        getContentPane().add(historico7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 580, 330, 30));

        dadosCliente.setBorder(null);
        dadosCliente.setOpaque(false);
        dadosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dadosClienteActionPerformed(evt);
            }
        });
        getContentPane().add(dadosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 220, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/históricoCliente.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, 603));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Cliente");
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 260, 70));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/Lista de Desejos.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 620, 120, 70));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/Adicionar pedido.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, 120, 70));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/Editar cadastro.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 570, 120, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastraCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastraCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastraCliente1ActionPerformed

    private void botaoRecomenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRecomenda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoRecomenda1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void historico2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historico2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historico2ActionPerformed

    private void historico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historico1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historico1ActionPerformed

    private void historico6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historico6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historico6ActionPerformed

    private void historico7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historico7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historico7ActionPerformed

    private void dadosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dadosClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dadosClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostraCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostraCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostraCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostraCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostraCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastraCliente1;
    private javax.swing.JButton botaoCadastraProduto1;
    private javax.swing.JButton botaoRecomenda1;
    private javax.swing.JButton botaoRegistra1;
    private javax.swing.JButton botaoRelatorio1;
    private javax.swing.JTextField dadosCliente;
    private javax.swing.JTextField historico1;
    private javax.swing.JTextField historico2;
    private javax.swing.JTextField historico3;
    private javax.swing.JTextField historico4;
    private javax.swing.JTextField historico5;
    private javax.swing.JTextField historico6;
    private javax.swing.JTextField historico7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
