/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.projempsoft;

/**
 *
 * @author Dandara
 */
public class PesquisaCliente extends javax.swing.JFrame {

    /**
     * Creates new form PesquisaCliente
     */
    public PesquisaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadastraCliente2 = new javax.swing.JButton();
        botaoRegistra2 = new javax.swing.JButton();
        botaoCadastraProduto2 = new javax.swing.JButton();
        botaoRelatorio2 = new javax.swing.JButton();
        botaoRecomenda2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        botaoCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoCadastraCliente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/b1se.png"))); // NOI18N
        botaoCadastraCliente2.setToolTipText("Cadastro de Clientes");
        botaoCadastraCliente2.setBorderPainted(false);
        botaoCadastraCliente2.setContentAreaFilled(false);
        getContentPane().add(botaoCadastraCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 370, 50));

        botaoRegistra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/b2se.png"))); // NOI18N
        botaoRegistra2.setToolTipText("Registro de Vendas");
        botaoRegistra2.setBorderPainted(false);
        botaoRegistra2.setContentAreaFilled(false);
        botaoRegistra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegistra2ActionPerformed(evt);
            }
        });
        getContentPane().add(botaoRegistra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 330, 70));

        botaoCadastraProduto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/b3se.png"))); // NOI18N
        botaoCadastraProduto2.setToolTipText("Cadastro de Produtos");
        botaoCadastraProduto2.setBorderPainted(false);
        botaoCadastraProduto2.setContentAreaFilled(false);
        botaoCadastraProduto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastraProduto2ActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCadastraProduto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 330, 90));

        botaoRelatorio2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/b4se.png"))); // NOI18N
        botaoRelatorio2.setToolTipText("Relatório de Vendas");
        botaoRelatorio2.setBorderPainted(false);
        botaoRelatorio2.setContentAreaFilled(false);
        getContentPane().add(botaoRelatorio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 330, 50));

        botaoRecomenda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/b5se.png"))); // NOI18N
        botaoRecomenda2.setToolTipText("Recomendações de Produtos");
        botaoRecomenda2.setBorderPainted(false);
        botaoRecomenda2.setContentAreaFilled(false);
        botaoRecomenda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRecomenda2ActionPerformed(evt);
            }
        });
        getContentPane().add(botaoRecomenda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 350, 80));

        jTextField2.setToolTipText("Digite o nome do cliente");
        jTextField2.setBorder(null);
        jTextField2.setOpaque(false);
        jTextField2.setVerifyInputWhenFocusTarget(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 370, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/campo2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 480, 80));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Pesquisa de Clientes");
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 500, 70));

        jTextField3.setEditable(false);
        jTextField3.setBorder(null);
        jTextField3.setHighlighter(null);
        jTextField3.setOpaque(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, 380, 40));

        jTextField4.setEditable(false);
        jTextField4.setBorder(null);
        jTextField4.setHighlighter(null);
        jTextField4.setOpaque(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 380, 40));

        jTextField5.setEditable(false);
        jTextField5.setBorder(null);
        jTextField5.setHighlighter(null);
        jTextField5.setOpaque(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 380, 40));

        jTextField6.setEditable(false);
        jTextField6.setBorder(null);
        jTextField6.setHighlighter(null);
        jTextField6.setOpaque(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, 380, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dandara\\Documents\\UFCG\\2015.1\\empsoft\\Usadas\\campo1.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, 430, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dandara\\Documents\\UFCG\\2015.1\\empsoft\\Usadas\\campo1.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 430, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dandara\\Documents\\UFCG\\2015.1\\empsoft\\Usadas\\campo1.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 430, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dandara\\Documents\\UFCG\\2015.1\\empsoft\\Usadas\\campo1.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 430, 60));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dandara\\Documents\\UFCG\\2015.1\\empsoft\\Usadas\\abrir(2).png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 710, 130, 50));

        botaoCadastrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dandara\\Documents\\UFCG\\2015.1\\empsoft\\Usadas\\b7se - Cópia.png")); // NOI18N
        botaoCadastrar.setToolTipText("");
        botaoCadastrar.setContentAreaFilled(false);
        getContentPane().add(botaoCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 710, 140, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/projempsoft/images/fundoa da tela de pesquisa de clientes - Cópia.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 1160, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoRegistra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegistra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoRegistra2ActionPerformed

    private void botaoCadastraProduto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastraProduto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastraProduto2ActionPerformed

    private void botaoRecomenda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRecomenda2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoRecomenda2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastraCliente2;
    private javax.swing.JButton botaoCadastraProduto2;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoRecomenda2;
    private javax.swing.JButton botaoRegistra2;
    private javax.swing.JButton botaoRelatorio2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
